services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    container_name: database
    environment:
      - POSTGRES_PASSWORD=fiapOn88
      - POSTGRES_DB=techChallenge
      
  app:
    image: cadupetinari88/techchallengefiapcadupetinari:v1
    ports:
      - "8080:8080"