services:
  app:
    image: techchallengefiapcadupetinari
    ports:
      - "8080:8080"

  database:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fiapOn88